### ISSUE TITLE
Example not running on OSX with 0.9+

### ISSUE THREAD

**Issue by elliotjpb** [bakercp/ofxIpVideoGrabber#17]
I have been having issues with getting the example code to run. I’ve tried the latest release as well as previous versions. When I use the project generator I add in ofxIpVideoGrabber and ofxXmlSettings. I then copy the example code in to the respective src files and put the xml file in the data folder. When I run the code I get quite a few errors, mostly regarding Threading. 

Suggestions on resolving this would be appreciated. 
Thanks!

**Comment by elliotjpb** [comment]
Thanks @bakercp for the speedy response!
Yes, so I am on OSX and I just pulled your changes and generated a new project with the project generator and included the addons and I got similar threading issues. 
The error was "No matching constructor for initialization of `std::unique_lock<std::mutex>`"

Was this correct or do I need to do something in the addon directory?

Thanks

**Comment by bakercp** [comment]
Hmm that is odd. What version of openFrameworks are you using?  If it's pre 0.9.0, then this addon probably won't work without getting an earlier release (from the releases tab).

**Comment by elliotjpb** [comment]
I'm running openFrameworks 0.9.1 with the latest release.

**Comment by bakercp** [comment]
Hm.. Very strange.  Can you post an image of your error output?

Also, can you try it with the latest release (0.9.3)?  Also, what version of xcode / osx are you using?

**Comment by elliotjpb** [comment]
Latest releaces - OSX 10.11.3. Xcode 7.2.1.

I'll try cloning 0.9.3 and try. 

Attached is the error output.
<img width="1138" alt="screen shot 2016-03-10 at 20 58 15" src="https://cloud.githubusercontent.com/assets/6968370/13684344/34c857a2-e703-11e5-84b3-924733cdc485.png">

**Comment by elliotjpb** [comment]
I am using a different project generator - "projectGeneratorSimple". 

<img width="1025" alt="screen shot 2016-03-10 at 21 13 09" src="https://cloud.githubusercontent.com/assets/6968370/13684761/0c80fc0c-e705-11e5-99af-ab5398976718.png">

I don't seem to have the one your using. Is this why?

**Comment by bakercp** [comment]
Most probably definitely. :)

If you download the release package http://openframeworks.cc/versions/v0.9.3/of_v0.9.3_osx_release.zip

Unzip it and look here:

![projectgenerator-osx](https://cloud.githubusercontent.com/assets/300484/13685122/98fb7012-e6d4-11e5-9eec-1a8095faea7b.png)

**Comment by bakercp** [comment]
Hmm. I'm not sure it's in a different repo and gets packaged during the release script process.  Closing this for now. Let me know if you run into any other problems. :)
