### ISSUE TITLE
Compile ofxIpVideoGrabber with android

### ISSUE THREAD

**Issue by elliotjpb** [bakercp/ofxIpVideoGrabber#19]
Is it possible to get ofxIpVideoGrabber to work with openFrameworks compiled on to android? Are there any particular steps?

Thanks
Elliot

**Comment by bakercp** [comment]
Sure it should work.  Have you tried it?  If so, what errors are you facing?

**Comment by elliotjpb** [comment]
I've done some tests. I got an IP cam stream set up and working with an oF project on OSX all working fine. I then have compiled on to android using the android studio set up. I have got it to run on the android device but I get a green coloured screen and in the console log it keeps trying to reconnect to the IP address. There are various exceptions along the way

`03-15 22:35:22.745 27600-27993/cc.openframeworks.CPdebugIP E/IPVideoGrabber: Exception : [http://192.168.0.3:8080/video]: I/O error: Permission denied`

It then ends with

`03-15 22:35:23.777 27600-28008/cc.openframeworks.CPdebugIP E/IPVideoGrabber: Exception : [http://192.168.0.3:8080/video]: I/O error: Permission denied
03-15 22:35:23.808 27600-27631/cc.openframeworks.CPdebugIP E/IPVideoGrabber: [http://192.168.0.3:8080/video] Connection retries exceeded, connection connection failed.  Call ::reset() to try again.`

Any ideas?
Thanks

**Comment by bakercp** [comment]
Did you add internet permissions to your android app?

https://stackoverflow.com/questions/2378607/what-permission-do-i-need-to-access-internet-from-an-android-application

**Comment by elliotjpb** [comment]
Ah! That was it thank you! Makes sense. It is working now, though very slow compared to a stream from the browser.

**Comment by bakercp** [comment]
Yeah, mjpeg streams are slow ... and require a lot of decoding processing power etc.  But glad it's working! :)
