### ISSUE TITLE
crashing on android

### ISSUE THREAD

**Issue by natxopedreira** [bakercp/ofxIpVideoGrabber#21]
Hi

On osx, android studio, 0f 0.9.3.

The project compiles ok, but it crashed on startup, to reproduce just:
- in header i put this:

```
#include "IPVideoGrabber.h"

using ofx::Video::IPVideoGrabber;
```

define an instance of the object, also in header:

`IPVideoGrabber vidrio;`

And the app crash on startup, im not using emulator, just runing on a device.

im doing something wrong?

**Comment by natxopedreira** [comment]
Solved, tried on another device and works as expected, thanks!

**Comment by bakercp** [comment]
Super!
