### ISSUE TITLE
_isConnected has incomplete type ‘std::atomic’

### ISSUE THREAD

**Issue by Wolftronics-SBC** [bakercp/ofxIpVideoGrabber#22]
error: field ‘_isConnected’ has incomplete type ‘std::atomic<bool>’

added
IPVideoGrabber.h
`
#include <atomic>`

**Comment by bakercp** [comment]
What version of openFrameworks are you using and what platform are you compiling for?

**Comment by Wolftronics-SBC** [comment]
ofx093 arch linux raspberry pi

**Comment by bakercp** [comment]
If you include 

```cpp
#include <atomic>
```

At the top of the file, does it work?  Perhaps it needs to be explicitly included on arch-linux?

ref
http://en.cppreference.com/w/cpp/atomic/atomic

**Comment by Wolftronics-SBC** [comment]
yes added, working...

**Comment by bakercp** [comment]
Super, just updated the file. Thanks for the report.
