### ISSUE TITLE
grabbing rtsp stream

### ISSUE THREAD

**Issue by hardjob** [bakercp/ofxIpVideoGrabber#25]
is there any way to grab rtsp stream ??

**Comment by bakercp** [comment]
This addon only works with mjpeg streams.  I believe broad stream support was just added to OSX in the master branch of openFrameworks (Linux already supports it via GStreamer).  

https://github.com/openframeworks/openFrameworks/pull/5530

Alternatively https://github.com/arturoc/ofxGStreamer should support it on OSX.
