### ISSUE TITLE
Net Exception

### ISSUE THREAD

**Issue by imthatoneguy** [bakercp/ofxIpVideoGrabber#8]
If I connect to two cameras simultaneously I get the error:

[ofxIPVideoGrabber:error] Exception : [bob]: Net Exception: Net subsystem not intitilized. 

The first setup camera will succeed but the second (bob) will produce this error.  Do you know where in the code IpVideoGrabber might be throwing this error?   

*It should be noted that this doesn't actually break the functionality, it's just an error printed to the console every time the app launches.*

Thanks!

**Comment by bakercp** [comment]
Closing this as 0.9.0 is the minimum supported.
